apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cloud9-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31234
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31235
  selector:
    run: webapp
  type: NodePort
status:
  loadBalancer: {}
