apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud9
  namespace: aluno1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
        - name: cloud9
          image: alanlab/cloud9-ruby265-rails523:v2
          ports:
          - containerPort: 8000
          envFrom:
          - secretRef: 
              name: auth
          volumeMounts:
          - mountPath: /code
            name: data
      volumes:
      - name: data
        hostPath:
          path: /tmp/aluno1
          type: DirectoryOrCreate   
